DROP DATABASE Library;

CREATE DATABASE Library;

SET @@global.time_zone = '+00:00';

USE Library;

CREATE TABLE Roles(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	role_name VARCHAR(50) NOT NULL
);

CREATE TABLE Users(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NUll,
	login VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL, 
	birth_date DATE NOT NULL,
	email VARCHAR(50) NOT NULL,
	phone VARCHAR(50) NOT NULL,
	role_id INT,
	FOREIGN KEY (role_id) REFERENCES Roles (id)
);

CREATE TABLE Book(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	author VARCHAR(50) NOT NUll,
	country VARCHAR(50) NOT NULL,
	language VARCHAR(50) NOT NULL,
	pages INT NOT NULL,
	year INT NOT NULL
);


CREATE TABLE Book_Issue(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	book_id INT,
	user_id INT,
	issue_date DATE NOT NUll,
	return_date DATE,
	FOREIGN KEY (book_id) REFERENCES Book (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE ON UPDATE CASCADE
);